### ISSUE TITLE
Task functionality Bugs

### ISSUE THREAD

**Issue by 7521468** [mir-ethernity/mir-eternal#126]
When a novice receives a task, the system will send 50 tokens, in some missions NONE
If you click the task transfer button, the transfer button is invalid。。。。 Border Village NPC, Piaoshiba quest, Find the Cat's treasure quest item is, hidden treasure, this item should be in the location of Border village, college, refresh multiple treasure chest, players open the treasure chest after the item, hidden treasure. 。。。NPC Tieniu quest, kill orcs and demonized orcs at designated locations. There is a problem with the number of monsters killed. For example, if the mission asks you to kill 10 monsters, the system will show 1/10 2/10 until 10/10 completes the monster battle mission, and the system will show 1/1 2/1 3/1 10/1 12/1 causing the monster killing mission to fail

**Comment by 7521468** [comment]
![CF34330B-7445-4CDC-BF02-B393A4559B2E](https://user-images.githubusercontent.com/112101165/189582687-e2101f92-af7e-45fd-82e0-6526c06b0f40.png)
![4562F2FA-C2D5-4D0A-9B3B-0287368B902A](https://user-images.githubusercontent.com/112101165/189582706-07c11b78-4fe4-4a69-b557-c91809764554.png)

**Comment by bernatvadell** [comment]
Thanks for report:
1) Fix quest progress for multiple monster to kills

**Comment by 7521468** [comment]
> Thanks for report:
> 
> 1. Fix quest progress for multiple monster to kills

Right! Check for other quests that require the killing of multiple monsters in the same quest

**Comment by bernatvadell** [comment]
> > Thanks for report:
> > 
> > 1. Fix quest progress for multiple monster to kills
> 
> Right! Check for other quests that require the killing of multiple monsters in the same quest

Implemented multiple progress
