### ISSUE TITLE
How to use Mir3DClientEditor and anyothersoft(like UE Viewer) to extract game models and textures for modification.

### ISSUE THREAD

**Issue by s01o** [mir-ethernity/mir-eternal#143]
How to use Mir3DClientEditor and anyothersoft(like UE Viewer) or any other way to extract game models and textures for modification.
I see that there is a decryptFolder in the Mir3DClientEditor, but after using it, other software still cannot operate it,they say it's still encrypted.

**Comment by s01o** [comment]
> At the moment it is not possible to extract the textures, we know how, but we have not had time to develop it.

Thank you very much for your reply.
I would like to ask you, whether the decryption method is already included in “Mir3DClientEditor”, because I feel that if the text can be seen, the size of the texture can also be seen, then it should be completely read. If you can give me a positive answer, I'll find other ways to help myself.

**Comment by bernatvadell** [comment]
Of course

https://github.com/Suprcode/mir-eternal/tree/main/Mir3DEditor/Mir3DCrypto

**Comment by bernatvadell** [comment]
Implemented the export and import of textures:
https://www.lomcn.net/forum/threads/mir3d-editor-0-2-0.110934
