### ISSUE TITLE
Achievements can be received indefinitely. After receiving, you can return or transfer to other maps. You have a chance to reset and receive repeatedly

### ISSUE THREAD

**Issue by 926cs** [mir-ethernity/mir-eternal#168]
Achievements can be received indefinitely. After receiving, you can return or transfer to other maps. You have a chance to reset and receive repeatedly
![image](https://user-images.githubusercontent.com/89799105/192089100-6b4bb5e4-0657-44ba-b477-ad0e5976e83a.png)

**Comment by bernatvadell** [comment]
fixed in the last commit:
https://github.com/mir-ethernity/mir-eternal/commit/45bfad4d8450238a90bbb4862d6912dc126d9d39
