### ISSUE TITLE
Update to the latest, no novice task, achievement system exception

### ISSUE THREAD

**Issue by 926cs** [mir-ethernity/mir-eternal#173]
Update to the latest, no novice task, achievement system exception
![image](https://user-images.githubusercontent.com/89799105/192638325-811af17b-a6c9-4741-a687-4b6de7377e3c.png)

**Comment by bernatvadell** [comment]
I am testing with the latest version v1.0.3.69 (185746) and it works fine.

![image](https://user-images.githubusercontent.com/17298604/192831254-82078e07-714f-433e-804e-65f49612b1fe.png)

**Comment by 926cs** [comment]
I continue to test and update the latest client
