### ISSUE TITLE
重铸系统单机测试没问题,如果服务端放到服务器上,不显示重铸属性

### ISSUE THREAD

**Issue by Powersongpower** [mir-ethernity/mir-eternal#182]
![QQ图片20220930081126](https://user-images.githubusercontent.com/112449915/193163283-ec1da86f-01c7-4a74-b3d1-b40fecc5d0ec.png)

**Comment by periko92** [comment]
Can you explain a bit more the bug?

Can you supply quest ID ?

**Comment by periko92** [comment]
![image](https://user-images.githubusercontent.com/109764547/193338636-5a230d55-71c4-4053-9f93-ad54736b873d.png)
as you can see, the NPC it's fine for me, i don't know why it shows wrong in your language.
Either the NPC text file at gameserver it looks the same.
{
  "Id": 612600000,
  "Content": "Reforging equipment can make your equipment more powerful in combat!<#SO:1>Reforge Weapons<#SO/><#SO:2>Reforge Armor<#SO/><#SO:3>Reforge Accessories<#SO/>"
}
