### ISSUE TITLE
open the store is empty

### ISSUE THREAD

**Issue by shumtn** [mir-ethernity/mir-eternal#204]
Brothers, we can't open the shop. Is this a bug? Or where do I need to set it? I compiled the latest code of the pull master
![store_error](https://user-images.githubusercontent.com/1932280/197331973-89fe02e7-062a-450d-a920-1b164c285c6f.png)

**Comment by bernatvadell** [comment]
That's because you are using an old client EXE, you have to use the original client exe and the latest server version.

**Comment by bernatvadell** [comment]
related to #50 and #15
