### ISSUE TITLE
Surver shutdown by itself!

### ISSUE THREAD

**Issue by Johnyl1** [mir-ethernity/mir-eternal#75]
Was playing in ST maze with Xena and the server shut down by itself when we killed a WhiteBoar. No errors on the VS windows tho!!!
![image](https://user-images.githubusercontent.com/63940002/186283423-98993aaa-7e04-4b8b-8b72-daf3328475bf.png)

When i try to restar the server gives this and stops loading on the "Loading Client data..."
![image](https://user-images.githubusercontent.com/63940002/186283844-ff59a433-565a-4a32-9431-8af593816a94.png)

if i press continue get this
![image](https://user-images.githubusercontent.com/63940002/186283987-02615edc-4b13-4a6b-9d38-0a973680e8d2.png)

**Comment by xiaozhu0232** [comment]
kill the white boar disconnect

**Comment by xiaozhu0232** [comment]
burrow zombie server crash

[2022/08/24 23:36:22]: The server has been successfully shut down

![image](https://user-images.githubusercontent.com/12591216/186461031-94c51969-82d7-4acb-a993-0bcf956f1436.png)

**Comment by itzdd9527** [comment]
please fix issues,thx！！！Game doesn't work！

**Comment by periko92** [comment]
Could you please post a log from /LOG/ folder?

**Comment by MirSoul** [comment]
Whether it is caused by translation errors.

I used the full set of information provided by the project team without collapse.

burrow zombie have no problem.

white boar were not tested.

**Comment by Johnyl1** [comment]
Not all white boars crash the server, coz we killed  a few til we got to that 1….

**Comment by MirSoul** [comment]
> 不是所有的白公猪都撞毁了服务器，coz我们杀了几只，直到我们到达那个1....

Therefore, it is more likely that a certain explosive item of the monster is not fully translated.
Do you use the full set of data files provided by the project team

**Comment by periko92** [comment]
> 

Dear, we're not using "translated item", all items still in chinese, do you have ID for whiteboar ?

**Comment by Johnyl1** [comment]
that zombie problem i had it with a wrong client version , now the boars never hapened, but ill try to find the boars id , problem is the server shuts down and theres no error on the debug window, only when i restart the server an error shows up....

**Comment by periko92** [comment]
I got the Boar ID. "Name" 白野猪 "ID" 1034
You can spawn ingame near guards @monster 白野猪 5

For me it doesn't crash.

![image](https://user-images.githubusercontent.com/109764547/186629355-2d7fa604-b223-4110-95f2-d62f9e6c030e.png)

**Comment by MirSoul** [comment]
Please package the “database” and “data.db” with your problem to the project team for testing,

I think this is the fastest solution.

> that zombie problem i had it with a wrong client version , now the boars never hapened, but ill try to find the boars id , problem is the server shuts down and theres no error on the debug window, only when i restart the server an error shows up....

**Comment by itzdd9527** [comment]
Now which client is correct?

**Comment by MirSoul** [comment]
> 现在哪个客户端是正确的？

I use [1.0.3.63], no problem

**Comment by periko92** [comment]
Im using 1.0.3.63 also, and there's no problem with Zombies, or White Boar.

**Comment by Johnyl1** [comment]
Like i said, we got to the maze , lilled a few , but only happened with that 1 inside the maze… btw we killed some inside the maze  before with no problems.

**Comment by MirSoul** [comment]
Hi, why don't you upload the data so that the project team can test.
It's a bit difficult for everyone to guess the problem.
Because every little detail can lead to big problems.

> Like i said, we got to the maze , lilled a few , but only happened with that 1 inside the maze… btw we killed some inside the maze before with no problems.

**Comment by periko92** [comment]
> burrow zombie server crash
> 
> [2022/08/24 23:36:22]: The server has been successfully shut down
> 
> ![image](https://user-images.githubusercontent.com/12591216/186461031-94c51969-82d7-4acb-a993-0bcf956f1436.png)

Zombie doesn't crash 
![image](https://user-images.githubusercontent.com/109764547/186639766-7d3cd6de-7588-4f43-9f13-ff9b04571354.png)

After killing it 
![image](https://user-images.githubusercontent.com/109764547/186639831-3d57b675-790b-4e32-b9b3-8562ca242952.png)

**Comment by Johnyl1** [comment]
Im gonna try to replicate the crash, i deleted all files coz u guys released new ones!! ill go back to ST with Xena!

**Comment by periko92** [comment]
> Im gonna try to replicate the crash, i deleted all files coz u guys released new ones!! ill go back to ST with Xena! What files do u need?

If you got crash again with WhiteBoar or Zombies, please post your User.db so we can replicate it..

As long im testing whiteboar and zombies , server doesn't crash, so must be on your side

**Comment by Johnyl1** [comment]
KK ill test it again, i can give u access to the server VMware if u need !

**Comment by itzdd9527** [comment]
Every time I test, I pull the latest code debug mode. Yesterday, I debug white boar and zombie. I will continue to test with the latest code.

**Comment by periko92** [comment]
> Every time I test, I pull the latest code debug mode. Yesterday, I debug white boar and zombie. I will continue to test with the latest code.

And did you have crash yesterday? Because today it's not crashing, just make sure you pull the latest "database"

**Comment by Johnyl1** [comment]
Might be an item on the Boar drop thats causing it!!!

**Comment by periko92** [comment]
> Might be an item on the Boar drop thats causing it!!!

Dear Johnyl1, we didn't change the drops for mobs, it should be any BUFF , but as i said, at the moment it's not crashing as you can see on my previous posts

**Comment by Johnyl1** [comment]
I just found out that the server crashes at lvl 60 , this bug might have happened becouse of that, me and Xena we were at lvl 59 when it happened, so one of us must have lvled up when we killed that whiteboar….

**Comment by MirSoul** [comment]
> 我刚刚发现服务器在lvl 60崩溃，这个错误可能发生在它，我和Xena在发生时我们在lvl 59，所以我们中的一个人一定在我们杀死那只白猪时已经崩溃了.

The experience multiplication rate is too high. If it exceeds the level after 60, resulting in experience overflow, please add the level attribute

**Comment by MirSoul** [comment]
> I just found out that the server crashes at lvl 60 , this bug might have happened becouse of that, me and Xena we were at lvl 59 when it happened, so one of us must have lvled up when we killed that whiteboar….

The experience multiplication rate is too high. If it exceeds the level after 60, resulting in experience overflow, please add the level attribute

**Comment by periko92** [comment]
> I just found out that the server crashes at lvl 60 , this bug might have happened becouse of that, me and Xena we were at lvl 59 when it happened, so one of us must have lvled up when we killed that whiteboar….

Dear, as i said on other issue opened by you, you need to increase the GrowthAttribute.txt to get max level, atm it's only coded til level 60,
If you want more levels, you can do it and pull the update :)

**Comment by Powersongpower** [comment]
我之前碰到过这样崩溃的问题，是因为怪物掉落配置问题，掉落物品“最小数量“大于“最大数量”的时候会出现。LOL!

**Comment by periko92** [comment]
> 我之前碰到过这样崩溃的问题，是因为怪物掉落配置问题，掉落物品“最小数量“大于“最大数量”的时候会出现。LOL!

Make a pillar so we can update it ;)

**Comment by bernatvadell** [comment]
We close task without activity. If the problem still occurs, please contact us.
